import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding party data...');

  const partyTypes = await prisma.partyType.findMany();
  
  if (partyTypes.length === 0) {
    console.log('No party types found. Please create party types first.');
    return;
  }

  const parties = [
    {
      partyName: 'ABC Textiles Pvt Ltd',
      partyCode: 'ABC001',
      address1: '123 Industrial Area',
      address2: 'Phase 2',
      address3: 'Sector 15',
      pincode: '600001',
      state: 'Tamil Nadu',
      district: 'Chennai',
      mobileNo: '9876543210',
      phoneNo: '0442345678',
      email: 'contact@abctextiles.com',
      panNo: 'ABCDE1234F',
      gstNo: '33ABCDE1234F1Z5',
      tallyAccName: 'ABC Textiles',
      creditDays: 30,
      active: 1,
    },
    {
      partyName: 'XYZ Fabrics Industries',
      partyCode: 'XYZ002',
      address1: '456 Textile Hub',
      address2: 'Main Road',
      pincode: '641001',
      state: 'Tamil Nadu',
      district: 'Coimbatore',
      mobileNo: '9876543211',
      email: 'info@xyzfabrics.com',
      panNo: 'XYZAB5678C',
      gstNo: '33XYZAB5678C1Z9',
      tallyAccName: 'XYZ Fabrics',
      creditDays: 45,
      active: 1,
    },
    {
      partyName: 'Global Garments Ltd',
      partyCode: 'GGL003',
      address1: '789 Export Zone',
      address2: 'SIPCOT Area',
      pincode: '600045',
      state: 'Tamil Nadu',
      district: 'Chennai',
      mobileNo: '9876543212',
      phoneNo: '0443456789',
      email: 'sales@globalgarments.com',
      panNo: 'GGLMN9012D',
      gstNo: '33GGLMN9012D1Z3',
      tallyAccName: 'Global Garments',
      creditDays: 60,
      active: 1,
    },
    {
      partyName: 'Supreme Cotton Mills',
      partyCode: 'SCM004',
      address1: '321 Mill Street',
      address2: 'Cotton Market',
      pincode: '625001',
      state: 'Tamil Nadu',
      district: 'Madurai',
      mobileNo: '9876543213',
      email: 'orders@supremecotton.com',
      panNo: 'SCMOP3456E',
      gstNo: '33SCMOP3456E1Z7',
      tallyAccName: 'Supreme Cotton',
      creditDays: 30,
      active: 1,
    },
    {
      partyName: 'Royal Dyeing Works',
      partyCode: 'RDW005',
      address1: '654 Dye House Lane',
      address2: 'Industrial Estate',
      pincode: '641602',
      state: 'Tamil Nadu',
      district: 'Tirupur',
      mobileNo: '9876543214',
      email: 'contact@royaldyeing.com',
      panNo: 'RDWQR7890F',
      gstNo: '33RDWQR7890F1Z1',
      tallyAccName: 'Royal Dyeing',
      creditDays: 15,
      active: 1,
    },
    {
      partyName: 'Modern Spinning Mills',
      partyCode: 'MSM006',
      address1: '987 Spinner Road',
      address2: 'SIDCO Complex',
      pincode: '638001',
      state: 'Tamil Nadu',
      district: 'Erode',
      mobileNo: '9876543215',
      email: 'info@modernspinning.com',
      panNo: 'MSMST1234G',
      gstNo: '33MSMST1234G1Z8',
      tallyAccName: 'Modern Spinning',
      creditDays: 45,
      active: 1,
    },
    {
      partyName: 'Elite Fashion Exports',
      partyCode: 'EFE007',
      address1: '147 Fashion Street',
      address2: 'Export Park',
      pincode: '600032',
      state: 'Tamil Nadu',
      district: 'Chennai',
      mobileNo: '9876543216',
      email: 'exports@elitefashion.com',
      panNo: 'EFEUV5678H',
      gstNo: '33EFEUV5678H1Z2',
      tallyAccName: 'Elite Fashion',
      creditDays: 60,
      active: 1,
    },
    {
      partyName: 'Prime Knitting Company',
      partyCode: 'PKC008',
      address1: '258 Knit Avenue',
      address2: 'Textile Zone',
      pincode: '641604',
      state: 'Tamil Nadu',
      district: 'Tirupur',
      mobileNo: '9876543217',
      email: 'sales@primeknitting.com',
      panNo: 'PKCWX9012I',
      gstNo: '33PKCWX9012I1Z6',
      tallyAccName: 'Prime Knitting',
      creditDays: 30,
      active: 1,
    },
    {
      partyName: 'Star Weaving Industries',
      partyCode: 'SWI009',
      address1: '369 Weaver Colony',
      address2: 'Power Loom Area',
      pincode: '638052',
      state: 'Tamil Nadu',
      district: 'Erode',
      mobileNo: '9876543218',
      email: 'contact@starweaving.com',
      panNo: 'SWIYZ3456J',
      gstNo: '33SWIYZ3456J1Z4',
      tallyAccName: 'Star Weaving',
      creditDays: 45,
      active: 1,
    },
    {
      partyName: 'Diamond Textile Processors',
      partyCode: 'DTP010',
      address1: '741 Process Lane',
      address2: 'Industrial Hub',
      pincode: '625010',
      state: 'Tamil Nadu',
      district: 'Madurai',
      mobileNo: '9876543219',
      email: 'info@diamondtextile.com',
      panNo: 'DTPAB7890K',
      gstNo: '33DTPAB7890K1Z0',
      tallyAccName: 'Diamond Textile',
      creditDays: 30,
      active: 1,
    },
    {
      partyName: 'Golden Thread Suppliers',
      partyCode: 'GTS011',
      address1: '852 Thread Market',
      address2: 'Commercial Street',
      pincode: '600079',
      state: 'Tamil Nadu',
      district: 'Chennai',
      mobileNo: '9876543220',
      email: 'orders@goldenthread.com',
      panNo: 'GTSCD1234L',
      gstNo: '33GTSCD1234L1Z5',
      tallyAccName: 'Golden Thread',
      creditDays: 15,
      active: 1,
    },
    {
      partyName: 'Sunrise Garment Manufacturers',
      partyCode: 'SGM012',
      address1: '963 Garment Street',
      address2: 'Manufacturing Zone',
      pincode: '641607',
      state: 'Tamil Nadu',
      district: 'Tirupur',
      mobileNo: '9876543221',
      email: 'sales@sunrisegarments.com',
      panNo: 'SGMEF5678M',
      gstNo: '33SGMEF5678M1Z9',
      tallyAccName: 'Sunrise Garments',
      creditDays: 60,
      active: 1,
    },
    {
      partyName: 'Perfect Prints & Designs',
      partyCode: 'PPD013',
      address1: '159 Print House',
      address2: 'Design Complex',
      pincode: '600058',
      state: 'Tamil Nadu',
      district: 'Chennai',
      mobileNo: '9876543222',
      email: 'contact@perfectprints.com',
      panNo: 'PPDGH9012N',
      gstNo: '33PPDGH9012N1Z3',
      tallyAccName: 'Perfect Prints',
      creditDays: 30,
      active: 1,
    },
    {
      partyName: 'Classic Cotton Traders',
      partyCode: 'CCT014',
      address1: '357 Cotton Exchange',
      address2: 'Market Yard',
      pincode: '638009',
      state: 'Tamil Nadu',
      district: 'Erode',
      mobileNo: '9876543223',
      email: 'info@classiccotton.com',
      panNo: 'CCTIJ3456O',
      gstNo: '33CCTIJ3456O1Z7',
      tallyAccName: 'Classic Cotton',
      creditDays: 45,
      active: 1,
    },
    {
      partyName: 'Mega Fabric Solutions',
      partyCode: 'MFS015',
      address1: '486 Solution Street',
      address2: 'Tech Park',
      pincode: '641012',
      state: 'Tamil Nadu',
      district: 'Coimbatore',
      mobileNo: '9876543224',
      email: 'sales@megafabric.com',
      panNo: 'MFSKL7890P',
      gstNo: '33MFSKL7890P1Z1',
      tallyAccName: 'Mega Fabric',
      creditDays: 30,
      active: 1,
    },
  ];

  for (const party of parties) {
    const created = await prisma.party.create({
      data: {
        ...party,
        partyTypes: {
          create: [
            {
              partyTypeId: partyTypes[0].id,
            },
          ],
        },
      },
    });
    console.log(`Created party: ${created.partyName}`);
  }

  console.log('Seeding completed!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
